config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root "notes#index"
  resources :notes do
    collection do
      get 'search'
    end
  end
  resources :connections, only: [:index]
  resources :users, only: [:edit, :update]
  resources :experiences
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/connection.rb
class Connection < ApplicationRecord
  belongs_to :user
end

app/models/experience.rb
class Experience < ApplicationRecord
  belongs_to :user, optional: true
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :user, optional: true
  validates :theme, presence: true, length: { maximum: 30}
  validates :details, presence: true, length: { maximum: 500}
  
  def self.search(search,id) 
    if search
      Note.where(['theme LIKE ?', "%#{search}%"]).where(user_id: id)
    else
      Note.all
    end
   
  end
end

app/models/note_tag.rb
class NoteTag < ApplicationRecord
  belongs_to :note
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :notes_tags
  has_many :notes, through: :notes_tags
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :notes
  has_many :connections
  has_many :experiences
  validates :nickname, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/connections_controller.rb
class ConnectionsController < ApplicationController
  def index
    @nickname = current_user.nickname
  end
  def new
    @connection = Connection.new
  end
  def create
    Connection.create!(connection_params)
    render :index
  end
  private
  def connection_params
    params.require(:connection).permit(:name, :details, :image, :preference, :dislike).merge(user_id: current_user.id)
  end
end

app/controllers/experiences_controller.rb
class ExperiencesController < ApplicationController

  def index
    # @data = { "2020-01-01" => 100,"2020-01-02" => 80}
    @experience = current_user.experiences
    # @day = Date.today 
    # @experience1 = @number.where(created_at: @day)
    # @experience = Experience.all
    @exp = current_user.experiences.where(created_at: Date.today.all_day)

    
    @experience.each do |experience| # each文でレコードを分ける。
      if (experience[:created_at].to_s.match(/#{Date.today.to_s}.+/)) 
    # Date.todayは、今日の年月日を取得できる。matchメソッドを使用し、hogeのレコード内に今日の年月日があるかどうか確認。
    # to_sで文字列に変換しているのは、matchメソッドは文字列にしか適用できないため。
        @data = experience[:number]  # レコードが今日に相当すれば、@dataに数字を代入。
        @experience1 = experience
      end

# hoge[:created_at]がJSTになっていない場合は、以下のようにしてJSTに変更できる。
# hoge_jst = hoge[:created_at].in_time_zone('Tokyo')

  end
end

  def new
    @experience = Experience.new
  end

  def create
    Experience.create!(experience_params)
    flash[:notice] = "話した人数が作成されました"
    redirect_to experiences_path
  end

  def edit
    @experience = Experience.find(params[:id])
  end

  def update
    experience = Experience.find(params[:id])
    experience.update(experience_params)
    flash[:notice] = "話した人数が更新されました"
    redirect_to experiences_path
  end

  def destroy
    experience = Experience.find(params[:id])
    experience.destroy
    flash[:notice] = "話した人数は削除されました"
    redirect_to experiences_path
  end

  private
  def experience_params
    params.require(:experience).permit(:number).merge(user_id: current_user.id)
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  
  def index
    @nickname = current_user.nickname
    sort = params[:sort] || "created_at DESC"
    @notes = current_user.notes.includes(:user).page(params[:page]).per(2).order(sort)
    
    if params[:option] == "created_at_desc" || params[:option] == nil
      @notes = current_user.notes.includes(:user).page(params[:page]).per(2).order('created_at DESC')
    elsif params[:option] == "created_at_asc"    
      @notes = current_user.notes.includes(:user).page(params[:page]).per(2).order('created_at ASC')
    end
  end

  def new
    @note = Note.new
  end

  def create

    @note = Note.new(note_params)
    if @note.save
      flash[:notice] = "ノートが作成されました"
      redirect_to controller: :notes, action: :index
    else
      render "new"
    end
  end

  def destroy
    note = Note.find(params[:id])
    note.destroy
    flash[:notice] = "ノートは削除されました"
    redirect_to root_path
  end


  def edit
    @note = Note.find(params[:id])
  end

  def update
    # note = Note.find(params[:id])
    # note.update(note_params)
    # flash[:notice] = "ノートは更新されました"
    # redirect_to root_path
    @note = Note.find(params[:id])
    if @note.update(note_params)
      flash[:notice] = "ノートが更新されました"
      redirect_to controller: :notes, action: :index
    else
      render "edit"
    end
  end

  def show
    @nickname = current_user.nickname
    @note = Note.find(params[:id])
  end

  def search
    @nickname = current_user.nickname
    @id = current_user.id
    sort = params[:sort] || "created_at DESC"
    @notes = Note.search(params[:keyword], current_user.id).page(params[:page]).per(2).order(sort)
    
    # sort = params[:sort] || "created_at DESC"
    # @notes = current_user.notes.includes(:user).page(params[:page]).per(2).order(sort)
    
    
  end

  private
  def note_params
    params.require(:note).permit(:theme, :details).merge(user_id: current_user.id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:nickname, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/connections_helper.rb
module ConnectionsHelper
end

app/helpers/experiences_helper.rb
module ExperiencesHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/connections/index.html.haml
.Wrapper
  .Top-contents
    %h1.Top-contents__title 
      = "#{@nickname} の Chat Note"

    = form_with url: search_notes_path, method: :get, class: "Search", local:true do |form|
      = form.text_field :keyword, placeholder: "テーマで検索", class: "Search__field"
      = form.submit value:"検索", class: "Search__btn"
  
  .Middle-contents
    .Sidebar
      %ul
        %li
          = link_to 'ネタ帳', root_path ,class: "btn"
        %li
          = link_to 'つながり', connections_path ,class: "btn"
        %li
          = link_to 'アカウント編集', edit_user_path(current_user) ,class: "btn"
        %li
          = link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'btn'
        %li
          = link_to 'つながりを登録',  new_connection_path ,class: "btn"
    
    .Main
      .Main_connection-wrap
        .Main_connection-wrap-item
          = image_tag("toshimasa.jpg", size: "100x100", alt: "画像", class: "connection_image")
          %p  川崎寿優
        .Main_connection-wrap-item
          = image_tag("toshimasa.jpg", size: "100x100", alt: "画像", class: "connection_image")
          %p  川崎寿優
        .Main_connection-wrap-item
          = image_tag("toshimasa.jpg", size: "100x100", alt: "画像", class: "connection_image")
          %p  川崎寿優
      
      
      
    
     
      
      

  

app/views/connections/new.html.haml
.Contents
  .Container
    %h1 つながりを記録する
    = form_with model: @connection, class: "Form", local:true do |form|
      %h2 イメージ画像
      = form.text_field :image, class:"Form__theme"
      %h2 名前
      = form.text_field :name, class:"Form__theme"
      %h2 好きな物事
      = form.text_field :preference, class: "Form__theme"
      %h2 嫌いな物事
      = form.text_field :dislike, class: "Form__theme"
      %h2 その他
      = form.text_field :details, class: "Form__details"
      = form.submit value:"記録する", class: "Form__btn" 
      

app/views/experiences/edit.html.haml
.Contents
  .Container
    %h1 ネタを記録する
    = form_with model: @experience, class: "Form", local:true do |form|
      %h2 話した人数
      = form.text_area :number,placeholder: "ちょっとしたネタ(その日あった出来事, 読んだ本, etc...)",  class: "Form__details"
      = form.submit value:"編集する", class: "Form__btn" 
      

app/views/experiences/index.html.haml
.Flex-wrapper
  .Sidebar-graph
    %ul
      %li
        = link_to 'ネタ帳', root_path ,class: "btn"
      %li
        = link_to '話した人数グラフ', experiences_path ,class: "btn"
      %li
        = link_to 'アカウント編集', edit_user_path(current_user) ,class: "btn"
      %li
        = link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'btn'
      %li
        = link_to 'ネタを書く',  new_note_path ,class: "btn"




  .Graph-wrapper
    %h1.Graph-wrapper__title 1日に話した人数の軌跡
    = line_chart @experience.group_by_day(:created_at).sum(:number), width: "800px", height: "500px"

    -if @exp.empty?
      %p
        = link_to '今日話した人数を記録', new_experience_path ,class: "Btn-wrapper__btn"
    -else
      %p.Graph-wrapper__number-title
        = "今日話した人数は#{@data}人です"
    -@exp.each do |experience|
      .Btn-wrapper
        %p
          = link_to '今日話した人数を編集', edit_experience_path(experience.id) ,class: "Btn-wrapper__btn"
        %p
          = link_to '削除', experience_path(experience.id), method: :delete, class: "Btn-wrapper__btn"


    -# %p 
    -#   = "今日話した人数は#{@data}人です"


  

        

app/views/experiences/new.html.haml
.Contents
  .Container
    %h1 話した人数を記録する
    = form_with model: @experience, class: "Graph-form", local:true do |form|
      %h2.Graph-form__title 話した人数
      .Graph-form__wrapper
        = form.text_field :number,  class: "Graph-form__details"
        = form.submit value:"記録する", class: "Graph-form__btn" 
      

app/views/layouts/_error_messages.html.haml
-if model.errors.any? 
  .alert-valid
    %ul
      -model.errors.full_messages.each do |message| 
        %li= message
      

app/views/layouts/_notifications.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ChatNote
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application'

  %body
    = render 'layouts/notifications'
    = yield

app/views/notes/_main-note.html.haml
.Wrapper
  .Top-contents
    %h1.Top-contents__title 
      = "#{@nickname} の Chat Note"

    = form_with url: search_notes_path, method: :get, class: "Search", local:true do |form|
      = form.text_field :keyword, placeholder: "テーマで検索", class: "Search__field"
      = form.submit value:"検索", class: "Search__btn"
  
  .Middle-contents
    .Sidebar
      %ul
        %li
          = link_to 'ネタ帳', root_path ,class: "btn"
        %li
          = link_to '話した人数グラフ', experiences_path ,class: "btn"
        %li
          = link_to 'アカウント編集', edit_user_path(current_user) ,class: "btn"
        %li
          = link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'btn'
        %li
          = link_to 'ネタを書く',  new_note_path ,class: "btn"
    
    .Main-wrapper
      .Main
        
        - @notes.each do |note|
          .Main__article.fadeInUp
            .Main__article-main
              .Main__article-main-wrapper
                %h1.Main__article-theme= note.theme
                %p.Main__article-date= note.created_at.strftime('%Y/%m/%d')
                %p.Main__article-details= truncate(note.details, :length => 226)
              %span.Nav_toggle
                %i  
                %i
                %i
                %nav.Nav
                  %ul.Nav__menu-ul
                    %li.Nav__menu-li 
                      = link_to '編集', edit_note_path(note.id), method: :get, class: "Nav__menu-li"
                    %li.Nav__menu-li 
                      = link_to '削除', note_path(note.id), method: :delete, class: "Nav__menu-li"
                    %li.Nav__menu-li 
                      = link_to '詳細', note_path(note.id), method: :get, class: "Nav__menu-li"
        = paginate @notes
      .Sort
        %select.Sort__search{:name => "search"}
          %option{:value => "basis"} ソート
          %option{:value => "created_at_desc"} 投稿日の新しい順
          %option{:value => "created_at_asc"} 投稿日の古い順


      -# = paginate @notes
      

app/views/notes/create.html.haml
%h3 記録が完了しました
= link_to 'マイページに戻る',root_path

app/views/notes/destroy.html.haml
%h3 削除が完了しました
= link_to 'マイページに戻る',root_path

app/views/notes/edit.html.haml
.Contents
  .Container
    %h1 ネタを編集する
    = form_with model: @note, class: "Form", local:true do |form|
      -if @note.errors.any? 
        -if @note.errors.include?(:theme) 
          %p.alert-valid
            =@note.errors.full_messages_for(:theme).first
        %h2 テーマ
        = form.text_field :theme, placeholder: "ネタのテーマ(スポーツ, 旅行, 季節 , 趣味, etc...)                 30文字以内", class:"Form__theme"
        


        -if @note.errors.include?(:details) 
          %p.alert-valid
            =@note.errors.full_messages_for(:details).first 
        %h2 詳細
        = form.text_area :details,placeholder: "ちょっとしたネタ(その日あった出来事, 読んだ本, etc...)      500文字以内" ,  class: "Form__details"
        -if @note.errors.include?(:details) 
          %p 
            =@note.errors.full_messages_for(:details).first 
        = form.submit value:"編集する", class: "Graph-form__btn"
        

        

      -else

        %h2 テーマ
        = form.text_field :theme, placeholder: "ネタのテーマ(スポーツ, 旅行, 季節 , 趣味, etc...)                 30文字以内", class:"Form__theme"
        %h2 詳細
        = form.text_area :details,placeholder: "ちょっとしたネタ(その日あった出来事, 読んだ本, etc...)      500文字以内" ,  class: "Form__details"
        = form.submit value:"編集する", class: "Graph-form__btn"

app/views/notes/escape.heml.haml
.Msin
  .l-side
    .search-sort
      .select-wrap
        %select{name: :sort_order, class: 'sort_order'}
          %option{value: "location.pathname", name: "location.pathname"} 
            並び替え
          %option{value: "price_asc"}
            価格の安い順
          %option{value: "price_desc"}
            価格の高い順
          %option{value: "created_at_asc"}
            出品の古い順
          %option{value: "created_at_desc"}
            出品の新しい順

app/views/notes/index.html.haml
= render partial: 'main-note'

app/views/notes/new.html.haml
.Contents
  .Container
    %h1 ネタを記録する
    = form_with model: @note, class: "Form", local:true do |form|
      -if @note.errors.any? 
        -if @note.errors.include?(:theme) 
          %p.alert-valid
            =@note.errors.full_messages_for(:theme).first
        %h2 テーマ
        = form.text_field :theme, placeholder: "ネタのテーマ(スポーツ, 旅行, 季節 , 趣味, etc...)                 30文字以内", class:"Form__theme"
        


        -if @note.errors.include?(:details) 
          %p.alert-valid
            =@note.errors.full_messages_for(:details).first 
        %h2 詳細
        = form.text_area :details,placeholder: "ちょっとしたネタ(その日あった出来事, 読んだ本, etc...)      500文字以内" ,  class: "Form__details"
        -if @note.errors.include?(:details) 
          %p 
            =@note.errors.full_messages_for(:details).first 
        = form.submit value:"記録する", class: "Graph-form__btn"
        

        

      -else

        %h2 テーマ
        = form.text_field :theme, placeholder: "ネタのテーマ(スポーツ, 旅行, 季節 , 趣味, etc...)                 30文字以内", class:"Form__theme"
        %h2 詳細
        = form.text_area :details,placeholder: "ちょっとしたネタ(その日あった出来事, 読んだ本, etc...)      500文字以内" ,  class: "Form__details"
        = form.submit value:"記録する", class: "Graph-form__btn"


       

app/views/notes/search.html.haml
.Wrapper
  .Top-contents
    %h1.Top-contents__title 
      = "#{@nickname} の Chat Note"

    = form_with url: search_notes_path, method: :get, class: "Search", local:true do |form|
      = form.text_field :keyword, placeholder: "テーマで検索", class: "Search__field"
      = form.submit value:"検索", class: "Search__btn"
  
  .Middle-contents
    .Sidebar
      %ul
        %li
          = link_to 'ネタ帳', root_path ,class: "btn"
        %li
          = link_to '話した人数グラフ', experiences_path ,class: "btn"
        %li
          = link_to 'アカウント編集', edit_user_path(current_user) ,class: "btn"
        %li
          = link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'btn'
        %li
          = link_to 'ネタを書く',  new_note_path ,class: "btn"
    
    .Main-wrapper
      .Main
        
        - @notes.each do |note|
          .Main__article.fadeInUp
            .Main__article-main
              .Main__article-main-wrapper
                %h1.Main__article-theme= note.theme
                %p.Main__article-date= note.created_at.strftime('%Y/%m/%d')
                %p.Main__article-details= truncate(note.details, :length => 226)
              %span.Nav_toggle
                %i  
                %i
                %i
                %nav.Nav
                  %ul.Nav__menu-ul
                    %li.Nav__menu-li 
                      = link_to '編集', edit_note_path(note.id), method: :get, class: "Nav__menu-li"
                    %li.Nav__menu-li 
                      = link_to '削除', note_path(note.id), method: :delete, class: "Nav__menu-li"
                    %li.Nav__menu-li 
                      = link_to '詳細', note_path(note.id), method: :get, class: "Nav__menu-li"
        = paginate @notes
      -# .Sort
      -#   %select.Sort__search{:name => "search"}
      -#     %option{:value => "basis"} ソート
      -#     %option{:value => "created_at_desc"} 投稿日時が新しい順
      -#     %option{:value => "created_at_asc"} 投稿日時が古い順

      .Sort
        %select.Sort__search{name: :sort_order, class: 'sort_order'}
          %option{value: "location.pathname", name: "location.pathname"} 
            ソート
          -# %option{value: "price_asc"}
          -#   価格の安い順
          -# %option{value: "price_desc"}
          -#   価格の高い順
          %option{value: "created_at_asc"}
            投稿日の古い順
          %option{value: "created_at_desc"}
            投稿日の新しい順

      -# = paginate @notes
      

app/views/notes/show.html.haml
.Wrapper

  .Top-contents
    %h1.Top-contents__title 
      = "#{@nickname} の Chat Note"

    = form_with url: search_notes_path, method: :get, class: "Search", local:true do |form|
      = form.text_field :keyword, placeholder: "テーマで検索", class: "Search__field"
      = form.submit value:"検索", class: "Search__btn"

  .Middle-contents
    .Sidebar
      %ul
        %li
          = link_to 'ネタ帳', root_path ,class: "btn"
        %li
          = link_to '話した人数グラフ', experiences_path ,class: "btn"
        %li
          = link_to 'アカウント編集', edit_user_path(current_user) ,class: "btn"
        %li
          = link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'btn'
        %li
          = link_to 'ネタを書く',  new_note_path ,class: "btn"
    
    .Main-show
      .Main-show__article-show
        .Main-show__article-main-show
          .Main-show__article-main-wrapper-show
            %h1.Main-show__article-theme-show= @note.theme
        
            %p.Main-show__article-details-show= @note.details
          %span.Nav_toggle-show
            %i  
            %i
            %i
          %nav.Nav-show
            %ul.Nav-show__menu-ul-show
              %li.Nav-show__menu-li-show
                = link_to '編集', edit_note_path(@note.id), method: :get, class: "Nav-show__menu-li-show"
              %li.Nav-show__menu-li-show
                = link_to '削除', note_path(@note.id), method: :delete, class: "Nav-show__menu-li-show"
              %li.Nav-show__menu-li-show
                = link_to '詳細', note_path(@note.id), method: :get, class: "Nav-show__menu-li-show"
      
      

  

app/views/notes/update.html.haml
%h3 編集が完了しました
= link_to 'マイページに戻る',root_path

app/views/users/edit.html.haml
.AccountPage
  .AccountPage__title
    %h2 Edit Account
    %h5 アカウントの編集
    = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'Button UserButton'
    = link_to "マイページに戻る", :back, class: 'Button UserButton'
  .AccountPage__form
    = form_for(current_user) do |f|
      .FormField
        .FormField__label--normal
          = f.label :nickname
        .FormField__input--normal
          = f.text_field :nickname, autofocus: true
      .FormField
        .FormField__label--normal
          = f.label :email
        .FormField__input--normal
          = f.email_field :email
      = f.submit "Update", class: 'Button UserButton'